; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop(loop-wrapper)' %s -S | FileCheck %s

; ModuleID = './nested_loops.c'
source_filename = "./nested_loops.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Function Attrs: nounwind uwtable
define dso_local void @nested_loops(i32 noundef %n, i32 noundef %m) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local void @nested_loops(
; CHECK-SAME: i32 noundef [[N:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP14]], label %[[FOR_COND1_PREHEADER_LR_PH:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH]]:
; CHECK-NEXT:    [[CMP212:%.*]] = icmp sgt i32 [[M]], 0
; CHECK-NEXT:    call void @loop_start()
; CHECK-NEXT:    br label %[[FOR_COND1_PREHEADER:.*]]
; CHECK:       [[FOR_COND1_PREHEADER]]:
; CHECK-NEXT:    [[I_015:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_LR_PH]] ], [ [[INC6:%.*]], %[[FOR_COND_CLEANUP3:.*]] ]
; CHECK-NEXT:    br i1 [[CMP212]], label %[[FOR_BODY4_PREHEADER:.*]], label %[[FOR_COND_CLEANUP3]]
; CHECK:       [[FOR_BODY4_PREHEADER]]:
; CHECK-NEXT:    call void @loop_start()
; CHECK-NEXT:    br label %[[FOR_BODY4:.*]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT_SPLIT:.*]]:
; CHECK-NEXT:    call void @loop_end()
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP_LOOPEXIT:.*]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND_CLEANUP3_LOOPEXIT_SPLIT:.*]]:
; CHECK-NEXT:    call void @loop_end()
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP3_LOOPEXIT:.*]]
; CHECK:       [[FOR_COND_CLEANUP3_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP3]]
; CHECK:       [[FOR_COND_CLEANUP3]]:
; CHECK-NEXT:    [[INC6]] = add nuw nsw i32 [[I_015]], 1
; CHECK-NEXT:    [[EXITCOND16_NOT:%.*]] = icmp eq i32 [[INC6]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND16_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT_SPLIT]], label %[[FOR_COND1_PREHEADER]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[FOR_BODY4]]:
; CHECK-NEXT:    [[J_013:%.*]] = phi i32 [ [[INC:%.*]], %[[FOR_BODY4]] ], [ 0, %[[FOR_BODY4_PREHEADER]] ]
; CHECK-NEXT:    call void (...) @side_effect() #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[J_013]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP3_LOOPEXIT_SPLIT]], label %[[FOR_BODY4]], !llvm.loop [[LOOP8:![0-9]+]]
;
entry:
  %cmp14 = icmp sgt i32 %n, 0
  br i1 %cmp14, label %for.cond1.preheader.lr.ph, label %for.cond.cleanup

for.cond1.preheader.lr.ph:                        ; preds = %entry
  %cmp212 = icmp sgt i32 %m, 0
  br label %for.cond1.preheader

for.cond1.preheader:                              ; preds = %for.cond1.preheader.lr.ph, %for.cond.cleanup3
  %i.015 = phi i32 [ 0, %for.cond1.preheader.lr.ph ], [ %inc6, %for.cond.cleanup3 ]
  br i1 %cmp212, label %for.body4, label %for.cond.cleanup3

for.cond.cleanup:                                 ; preds = %for.cond.cleanup3, %entry
  ret void

for.cond.cleanup3:                                ; preds = %for.body4, %for.cond1.preheader
  %inc6 = add nuw nsw i32 %i.015, 1
  %exitcond16.not = icmp eq i32 %inc6, %n
  br i1 %exitcond16.not, label %for.cond.cleanup, label %for.cond1.preheader, !llvm.loop !5

for.body4:                                        ; preds = %for.cond1.preheader, %for.body4
  %j.013 = phi i32 [ %inc, %for.body4 ], [ 0, %for.cond1.preheader ]
  call void (...) @side_effect() #2
  %inc = add nuw nsw i32 %j.013, 1
  %exitcond.not = icmp eq i32 %inc, %m
  br i1 %exitcond.not, label %for.cond.cleanup3, label %for.body4, !llvm.loop !8
}

declare void @side_effect(...) local_unnamed_addr #1

attributes #0 = { nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { nounwind }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 1}
!4 = !{!"Ubuntu clang version 14.0.0-1ubuntu1.1"}
!5 = distinct !{!5, !6, !7}
!6 = !{!"llvm.loop.mustprogress"}
!7 = !{!"llvm.loop.unroll.disable"}
!8 = distinct !{!8, !6, !7}
;.
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]], [[META7:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META7]] = !{!"llvm.loop.unroll.disable"}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META6]], [[META7]]}
;.
